spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
  graphql:
    globalcors:
      allowed-origins: "*"
      allowedHeaders: "*"
      allowedMethods: "*"
